### ISSUE TITLE
mac 下寄了

### ISSUE THREAD

**Issue by anyhl** [gnibuoz/QRibbon#5]
![image](https://user-images.githubusercontent.com/49542737/217998223-8636ea8c-2253-4be6-8040-1cb1b37fb913.png)

**Comment by gnibuoz** [comment]
感谢反馈，看图片样子应该是标题栏定制的问题，估计Mac下要做单独处理，之前在Linux上测试过没啥大问题，Mac还真没测过，最近实在没哈时间，得空了看下

**Comment by anyhl** [comment]
![image](https://user-images.githubusercontent.com/49542737/232722286-c2e0d24e-cf02-4e04-83df-0a6b1019e9d2.png)
增加这个

**Comment by gnibuoz** [comment]
> ![image](https://user-images.githubusercontent.com/49542737/232722286-c2e0d24e-cf02-4e04-83df-0a6b1019e9d2.png) 增加这个

已提交至仓库，感谢！
